name: pemrograman_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"   # ✅ perbaikan: environment harus pakai range, bukan ^

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 🔹 Local storage & utils
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2    # ✅ dipakai AuthService/UserService versi lokal
  uuid: ^4.4.2                  # ✅ dipakai untuk id di ExpenseService
  crypto: ^3.0.3                # (opsional) kalau masih dipakai untuk hashing

  # 🔹 Fitur tambahan aplikasi kamu
  csv: ^5.0.2
  fl_chart: ^0.66.2
  share_plus: ^10.0.2
  pdf: ^3.11.0
  printing: ^5.13.1
  provider: ^6.1.2
  http: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/Expense.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Expense.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground_scale_factor: 0.5
  adaptive_icon_background: "#FFFFFF"