// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduLQw31F4mgI7AOL9t9bu1m_CsX0pRv4',
    appId: '1:879461059185:web:305583201ecd78a1d669d0',
    messagingSenderId: '879461059185',
    projectId: 'multiuser-expense-ilham',
    authDomain: 'multiuser-expense-ilham.firebaseapp.com',
    storageBucket: 'multiuser-expense-ilham.firebasestorage.app',
    measurementId: 'G-HLSLBTMHVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8SX78zVKZa3_geimA1fzlF5dWnmeYPI',
    appId: '1:879461059185:android:5a6a7d58474989ced669d0',
    messagingSenderId: '879461059185',
    projectId: 'multiuser-expense-ilham',
    storageBucket: 'multiuser-expense-ilham.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgYW93tB6p3FSRPn1k73O_zqnRwLsczV8',
    appId: '1:879461059185:ios:c10b5309ee1042fcd669d0',
    messagingSenderId: '879461059185',
    projectId: 'multiuser-expense-ilham',
    storageBucket: 'multiuser-expense-ilham.firebasestorage.app',
    iosBundleId: 'com.example.pemrogramanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgYW93tB6p3FSRPn1k73O_zqnRwLsczV8',
    appId: '1:879461059185:ios:c10b5309ee1042fcd669d0',
    messagingSenderId: '879461059185',
    projectId: 'multiuser-expense-ilham',
    storageBucket: 'multiuser-expense-ilham.firebasestorage.app',
    iosBundleId: 'com.example.pemrogramanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDduLQw31F4mgI7AOL9t9bu1m_CsX0pRv4',
    appId: '1:879461059185:web:290dec351dc0e553d669d0',
    messagingSenderId: '879461059185',
    projectId: 'multiuser-expense-ilham',
    authDomain: 'multiuser-expense-ilham.firebaseapp.com',
    storageBucket: 'multiuser-expense-ilham.firebasestorage.app',
    measurementId: 'G-LRMTLZSQRB',
  );
}
